[theme]
primaryColor = "#E53935"
backgroundColor = "#F7F7F5"
secondaryBackgroundColor = "#FFFFFF"
textColor = "#0A0A0A"
font = "sans serif"

[server]
headless = true
enableCORS = false
enableXsrfProtection = true
